### PR TITLE
chore: Release python sdk schema version 0.2.3

### PR DESCRIPTION
**Pull request by selcukcihan**
Related to https://linear.app/serverless/issue/SC-1166#comment-9723da2b

### CODE REVIEW

**Comment by selcukcihan** [comment]
@medikoo ready for review please

**Review by medikoo — APPROVED** [review]
👍

**Comment by medikoo** [comment]
@selcukcihan can we also release AWS Lambda SDK with latest changes ASAP? (also it'll be good that we follow up releases shortly after important updates)

**Comment by selcukcihan** [comment]
> @selcukcihan can we also release AWS Lambda SDK with latest changes ASAP? (also it'll be good that we follow up releases shortly after important updates)

👍  https://github.com/serverless/console/pull/808

**Pull request merged**
