### PR TITLE
Remove blinker dependency

### PR DESCRIPTION
**Pull request by selcukcihan**
### Description
* Related issue https://linear.app/serverless/issue/SC-593/python-sdk-big-latency-overhead#comment-ed4329da
* Remove blinker usage and use a simple pub/sub logic
* Blinker dependency is still needed in case of flask instrumentation, so it's still packaged.

### Testing done
Unit tested

### CODE REVIEW

**Comment by selcukcihan** [comment]
@medikoo ready for review please

**Review by medikoo — COMMENTED** [review]
If we improved the initialization time, it'll be good to narrow the initialization duration threshold in performance test

**Comment by selcukcihan** [comment]
> If we improved the initialization time, it'll be good to narrow the initialization duration threshold in performance test

Yes, we did improve init time, I've reduced it to 400ms now.

**Review by medikoo — APPROVED** [review]
👍

**Pull request merged**
