### PR TITLE
AWS Lambda Python SDK release v0.1.1

### PR DESCRIPTION
**Pull request by selcukcihan**
To fix the problem mentioned in https://github.com/serverless/console/pull/496#issuecomment-1458361252

### CODE REVIEW

**Review by medikoo — APPROVED** [review]
👍

**Comment by selcukcihan** [comment]
This one had an error as well https://github.com/serverless/console/actions/runs/4355951911/jobs/7613274197

```
2023-03-07T15:50:09.3451496Z /home/runner/work/console/console/node/node_modules/essentials/index.js:21
2023-03-07T15:50:09.3452008Z 		throw reason;
2023-03-07T15:50:09.3452268Z 		^
2023-03-07T15:50:09.3452402Z 
2023-03-07T15:50:09.3454923Z AccessDenied: Access Denied
2023-03-07T15:50:09.3458435Z     at throwDefaultError (/home/runner/work/console/console/node/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
2023-03-07T15:50:09.3461844Z     at deserializeAws_restXmlGetObjectCommandError (/home/runner/work/console/console/node/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4356:51)
2023-03-07T15:50:09.3462744Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-03-07T15:50:09.3465921Z     at async /home/runner/work/console/console/node/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
2023-03-07T15:50:09.3467008Z     at async /home/runner/work/console/console/node/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
2023-03-07T15:50:09.3467979Z     at async /home/runner/work/console/console/node/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
2023-03-07T15:50:09.3469321Z     at async /home/runner/work/console/console/node/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
2023-03-07T15:50:09.3470508Z     at async /home/runner/work/console/console/node/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
2023-03-07T15:50:09.3519772Z     at async /home/runner/work/console/console/node/lib/publish-public-layers.js:39:15
2023-03-07T15:50:09.3525373Z     at async Promise.all (index 0)
2023-03-07T15:50:09.3526025Z     at async module.exports (/home/runner/work/console/console/node/lib/publish-public-layers.js:34:5) {
2023-03-07T15:50:09.3526448Z   '$fault': 'client',
2023-03-07T15:50:09.3526725Z   '$metadata': {
2023-03-07T15:50:09.3526985Z     httpStatusCode: 403,
2023-03-07T15:50:09.3527368Z     requestId: 'C10ZWEM0DXBPW6PV',
2023-03-07T15:50:09.3528008Z     extendedRequestId: 'O78k+PtAbdZ4gmAq+zYQUewmChPDy0/XScnOLaJ1mq0iMQjC7hjVHtFSclfP6OT38Fc81rF8m5c=',
2023-03-07T15:50:09.3528449Z     cfId: undefined,
2023-03-07T15:50:09.3528693Z     attempts: 1,
2023-03-07T15:50:09.3528943Z     totalRetryDelay: 0
2023-03-07T15:50:09.3529176Z   },
2023-03-07T15:50:09.3529463Z   Code: 'AccessDenied',
2023-03-07T15:50:09.3529815Z   RequestId: 'C10ZWEM0DXBPW6PV',
2023-03-07T15:50:09.3530399Z   HostId: 'O78k+PtAbdZ4gmAq+zYQUewmChPDy0/XScnOLaJ1mq0iMQjC7hjVHtFSclfP6OT38Fc81rF8m5c='
2023-03-07T15:50:09.3530806Z }
2023-03-07T15:50:09.3631711Z ##[error]Process completed with exit code 1.
```

Is this an IAM issue? Or is it an issue with a non-existent resource maybe?

@medikoo

**Comment by medikoo** [comment]
@selcukcihan I've looked into that, and the publication script assumes that the registry file already exists. I've relaxed that in this PR: https://github.com/serverless/console/pull/498

Once it's merged, we will, unfortunately, need to again re-release

**Comment by medikoo** [comment]
@selcukcihan it should be fixed now. Sorry for hassle, but can you create another release PR?

**Comment by selcukcihan** [comment]
> @selcukcihan it should be fixed now. Sorry for hassle, but can you create another release PR?

Sure, no problem https://github.com/serverless/console/pull/499

**Comment by medikoo** [comment]
@selcukcihan there were still some issues with layers publication script, yet to move with that faster I've just pushed changes directly to `main`. 

There was also minor issue in CI script, which provided Github tag, which is used only if we want to upload layers arn map to GitHub release. Ci failed because `GITHUB_TOKEN` was not provided in env variables. Yet  I've removed that argument completely (https://github.com/serverless/console/commit/47c0771d6caeeb281fb3391d1242ef593d398a9e), as currently we don't publish GitHub releases, as it's the case with Node.js. One day it'll be great to do that, for timebeing that's easier route.

So after few bumps we have successful release of v0.1.5 🎉

**Pull request merged**
