### PR TITLE
chore: Release v0.5.7

### PR DESCRIPTION
**Pull request by Danwakeem**

### CODE REVIEW

**Comment by medikoo** [comment]
@Danwakeem dev mode integration tests failed recently: https://github.com/serverless/console/actions/runs/4047373675/jobs/6961322081#step:11:16339 so it may not fulfill

**Comment by Danwakeem** [comment]
@medikoo i am guessing it may have just been some flakiness of the tests because I re ran these and they passed 🤷‍♂️

**Comment by medikoo** [comment]
> @medikoo i am guessing it may have just been some flakiness of the tests because I re ran these and they passed 🤷‍♂️

I guess it's some rare condition that probably can be read from logs and possibly prevented in the future. Anyway let's not block this

**Review by medikoo — APPROVED** [review]
👍

**Pull request merged**
