### PR TITLE
[Python Lambda SDK] Enable mypy & fix type checker errors

### PR DESCRIPTION
**Pull request by selcukcihan**
### Description
* Related issue https://linear.app/serverless/issue/SC-628/python-sdk-type-checking
* Fix mypy type checking errors in Lambda SDK

### Testing done
CI flow should validate the changes by type-checking and unit testing.

### CODE REVIEW

**Comment by selcukcihan** [comment]
@medikoo ready for review please 🙏

**Comment by selcukcihan** [comment]
@medikoo just a reminder in case this went unnoticed

**Review by medikoo — CHANGES_REQUESTED** [review]
@selcukcihan sorry for missing that, still it has now conflicts, can you rebase with main?

**Review by medikoo — APPROVED** [review]
👍

**Comment by medikoo** [comment]
@selcukcihan It still cannot be merged: 

Screenshot 2023-05-09 at 13 55 17

**Comment by selcukcihan** [comment]
I've rebased from main, should be good now 👍

**Pull request merged**
