### PR TITLE
Updated req/res schema

### PR DESCRIPTION
**Pull request by Danwakeem**
## Description
Just updating the proto schema to match the new version that will be in the sdk

### CODE REVIEW

**Review by medikoo — APPROVED** [review]
👍

**Comment by Danwakeem** [comment]
Thanks @medikoo 😎 Just double checking the req/res updates have not been released yet correct? I will take this PR out of draft once that change goes out

**Comment by medikoo** [comment]
@Danwakeem There are integration fails, as I investigated due to issues in AWS CW logs service (not all functions logs are returned as expected). Nonetheless I've prepared release: https://github.com/serverless/console/pull/292 If CI fail for same reason I'll push tag manually

**Comment by Danwakeem** [comment]
Ahh okay cool thanks @medikoo I will go ahead and open this PR so I can merge this in once that is all green 😎

**Pull request merged**
