### PR TITLE
Add aws lambda trace spans

### PR DESCRIPTION
**Pull request by selcukcihan**
### Description
* Related issue https://linear.app/serverless/issue/SC-356/aws-lambda-sdk-create-lambda-process-trace-spans-with-related-tags
* Add AWS Lambda Trace spans (root span, initialization and invocation)
* Print the trace at the end

### Testing done
Tested with unit tests to ensure
  * lambda spans are created
  * tags are attached

### CODE REVIEW

**Comment by selcukcihan** [comment]
@medikoo the tests in CI are failing because we haven't yet published new base SDK version, however the tests and new functionality depend on that new version.

**Review by medikoo — CHANGES_REQUESTED** [review]
> @medikoo the tests in CI are failing because we haven't yet published new base SDK version, however the tests and new functionality depend on that new version.

@selcukcihan  Tests should not depend on PyPI release. It's only dependencies of `aws-lambda-sdk` which should be taken from PyPi, but otherwise `aws-lambda-sdk` logic should be tested against code that's in repository.

**Comment by selcukcihan** [comment]
> > @medikoo the tests in CI are failing because we haven't yet published new base SDK version, however the tests and new functionality depend on that new version.
> 
> @selcukcihan Tests should not depend on PyPI release. It's only dependencies of `aws-lambda-sdk` which should be taken from PyPi, but otherwise `aws-lambda-sdk` logic should be tested against code that's in repository.

I'm a bit confused on this matter, this is the exact opposite of what you've mentioned in https://github.com/serverless/console/pull/464#pullrequestreview-1307810730 and which resulted in https://github.com/serverless/console/pull/473

**Comment by medikoo** [comment]
> I'm a bit confused on this matter, this is the exact opposite of what you've mentioned in #464 (review) and which resulted in #473

No, It says the same thing :)

Note we're in context of `aws-lambda-sdk` package, and in https://github.com/serverless/console/pull/464#pullrequestreview-1307810730 I mention that we need to rely on `sdk` and `sdk-schema` __dependencies__ as being taken from PyPI not repository (I'm not speaking about `aws-lambda-sdk` of which logic we need test as is in repository, but of its dependencies).

And same thing I mention again here, that it's __only dependencies of aws-lambda-sdk which should be taken from PyPi__

If reasoning for that is not clear, please revisit my comment here: https://github.com/serverless/console/pull/464#issuecomment-1438825216

**Comment by selcukcihan** [comment]
> > I'm a bit confused on this matter, this is the exact opposite of what you've mentioned in #464 (review) and which resulted in #473
> 
> No, It says the same thing :)
> 
> Note we're in context of `aws-lambda-sdk` package, and in [#464 (review)](https://github.com/serverless/console/pull/464#pullrequestreview-1307810730) I mention that we need to rely on `sdk` and `sdk-schema` **dependencies** as being taken from PyPI not repository (I'm not speaking about `aws-lambda-sdk` of which logic we need test as is in repository, but of its dependencies).
> 
> And same thing I mention again here, that it's **only dependencies of aws-lambda-sdk which should be taken from PyPi**
> 
> If reasoning for that is not clear, please revisit my comment here: [#464 (comment)](https://github.com/serverless/console/pull/464#issuecomment-1438825216)

Ok I think I misunderstood your first comment, when I mentioned
> the tests in CI are failing because we haven't yet published new base SDK version, however the tests and new functionality depend on that new version.

And you came with

> Tests should not depend on PyPI release. It's only dependencies of aws-lambda-sdk which should be taken from PyPi, but otherwise aws-lambda-sdk logic should be tested against code that's in repository.

I somehow 😄 got the impression that you were making a counter point. All good now, let me lay out my understanding just in case:

1. Unit tests of package X should install all of package X dependencies (be it from another package in the monorepo, be it an external dependency) from pypi only. Package X should not be from pypi, it should be the latest in the repo against which we are trying to validate the state of things.
2. Integration tests that test lambda layers, these tests should run against lambda layers published by the test script, ~~where layer source is built from the latest in the main branch~~ where layer source is built from the latest among all our packages in the main branch.

In this case, we need to release a new version of the base SDK, so that this PR's CI flow succeeds. Would you like me to create a release PR for base SDK?

**Comment by medikoo** [comment]
> Integration tests that test lambda layers, these tests should run against lambda layers published by the test script, where layer source is built from the latest in the main branch where layer source is built from the latest among all our packages in the main branch.

Integration tests should be run against the same state of things as unit tests, so Package X should be taken latest from repo, but its dependencies from PyPI (for very same reasons why we run unit tests that way)

and.. yes, as we introduced fixes to SDK with prior PR's, we need to publish updated version of it  first - and this is the part where I got confused :) I thought you mention that we need to publish AWS Lambda SDK first.. while you meant SDK - that's totally correct

**Comment by selcukcihan** [comment]
I've pushed a fix with https://github.com/serverless/console/pull/486/commits/9ef8437eeef5678ffdf0e36c289c4b0c0b908243 it fixes a weird case with the `betterproto` library regarding handling of byte arrays (concerning span.id, span.trace_id and span.parent_span_id fields)

### Further Testing
Regarding https://linear.app/serverless/issue/SC-220#comment-e8974ca0

I've created a layer in my account using this branch as source, the ARN is `arn:aws:lambda:eu-west-1:692593327170:layer:sls-sdk-python:63`.

1. Create a python lambda function (runtime python3.9) with following env variables:
* `AWS_LAMBDA_EXEC_WRAPPER`: `/opt/sls-sdk-node/exec-wrapper.sh`
* `SLS_ORG_ID`: "YOUR_SLS_ORG_ID"

Attach `arn:aws:lambda:eu-west-1:692593327170:layer:sls-sdk-python:63` as a layer. And publish a version of your function now.

Example:
Screenshot 2023-03-03 at 16 12 44

2. Select the function for traces in the console:
Screenshot 2023-03-03 at 16 14 01

3. After doing this, console updates your function configuration (adds sls-sdk-node layer which is not compatible with our test purpose) so you need to test using the version of your function that you've published in step 1. Invoke your function and you should see a trace on the console like this:

Screenshot 2023-03-03 at 16 18 24

### Problems
While doing this test, I've noticed following issues:
1. The `aws.lambda.invocation` span shows an invalid negative value. When I looked into the specific values, it seems like the invocation was too fast and it somehow overflows. But I can't see a problem in the trace data, it might be an issue with the console UI maybe? This is the data (notice the sub millisecond difference):
```
>>> payload.spans[2].name
'aws.lambda.invocation'
>>> payload.spans[2].end_time_unix_nano - payload.spans[2].start_time_unix_nano
465497
```

2. Logs seem to be appearing twice as in below. This is related to the logging configuration of the lambda SDK, I'm still exploring how best to configure logging. Our current logging configuration is broken.
Screenshot 2023-03-03 at 16 22 00

3. The layer can only be used with Python3.9 runtime. It won't run with 3.7 or 3.8. I think we need to be publishing separate layers for each of these runtimes. Like for instance DataDog provides a separate layer for each runtime https://pypi.org/project/datadog-lambda/2.19.0/ Example: ARN `arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Python37:1` would be for Python3.7. This will need some setup in our CI pipeline.

**Review by medikoo — CHANGES_REQUESTED** [review]
@selcukcihan Thanks for update! I've tried to setup this locally and approached following issues:

1. When installing `aws-lambda-sdk` dependencies with `python3 -m pip install --editable`
Installer printed error:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paddlepaddle 2.3.2 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 4.22.0 which is incompatible.
```

Can we fix that conflict?

2. After I've installed the packages locally I've noticed many new untracked files in repository, Can we ensure that any build results are covered in `.gitignore` ?


3. I've run integration tests configured at https://github.com/serverless/console/pull/483 and outcome is as follows:

Screenshot 2023-03-03 at 15 58 07

As I investigated that deeper, the outcome is as follows:
- for `python3.7`, runtime trace is not written at all
- `python3.8` success invocation crashes with  `[ERROR] Runtime.ImportModuleError: Unable to import module 'serverless_aws_lambda_sdk.internal_extension.wrapper': No module named 'serverless_aws_lambda_sdk'`
- In `python3.9` trace is written. Yet spans are listed out of creation order (it's not a big issue per se, but it'll be good to ensure the same deterministic ordering as it's in Node.js case where spans are ordered by start date). I've relaxed the test to see if it's the only issue, yet then it failed, not finding a single `aws...` tag reported (the first check is on `aws.lambda.isColdstart`)
- In error cases traces are not written.

If for some reason ensuring support for each Python version requires some specific amount of work, for now we can focus on single version. Let me know

**Comment by selcukcihan** [comment]
> 1. When installing aws-lambda-sdk dependencies with python3 -m pip install --editable
Installer printed error:

I don't get this error, I've created a fresh venv with:
```
python3.9 -m venv .venv
source .venv/bin/activate
```

And then:
```
cd python/packages/aws-lambda-sdk
python3 -m pip install --editable .
```

successfully.

The error you got mentions a package named `paddlepaddle` which is not a dependency of our package, not even transiently. I think this is a problem with your python environment, can you try the steps I mentioned above and try to build it in a fresh virtual environment please?

**Comment by selcukcihan** [comment]
> If for some reason ensuring support for each Python version requires some specific amount of work, for now we can focus on single version. Let me know

Yes, currently I'm working with Python3.9 only. It will require some work to
1. Release lambda layer Python 3.7 & 3.8 (CI/CD)
2. Make sure code is compatible with Python 3.7 & 3.8

I think it would be easier to make it compatible for older versions once we have a sound baseline that is validated with integration tests.

**Comment by selcukcihan** [comment]
> In python3.9 trace is written. Yet spans are listed out of creation order (it's not a big issue per see, but it'll be good to ensure the same deterministic ordering as it's in Node.js case where spans are ordered by start date). I've relaxed the test to see if it's the only issue, yet then it failed, not finding a single aws... tag reported (the first check is on aws.lambda.isColdstart)
> In error cases traces are not written.

I'm trying to run the integration tests to reproduce these issues. I've merged the integration test branch locally but currently I'm stuck with this error from aws-sdk `CredentialsProviderError: Could not load credentials from any providers`

Dumping my trials and findings here, in case you've seen it before and might be able to help.

```
➜  aws-lambda-sdk git:(sc-356-integ-test) ✗ ../../../node_modules/mocha/bin/mocha trysts.js
  0 passing (0ms)

CredentialsProviderError: Could not load credentials from any providers
    at /Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13:11
    at /Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:533:9)
    at process.processTimers (node:internal/timers:507:7)
    at async coalesceProvider (/Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)
    at async SignatureV4.credentialProvider (/Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:33:24)
    at async SignatureV4.signRequest (/Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/signature-v4/dist-cjs/SignatureV4.js:87:29)
    at async /Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:16:18
    at async /Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22 {
  tryNextLink: false,
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
CredentialsProviderError: Could not load credentials from any providers
    at /Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13:11
    at /Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async coalesceProvider (/Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)
    at async SignatureV4.credentialProvider (/Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:33:24)
    at async SignatureV4.signRequest (/Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/signature-v4/dist-cjs/SignatureV4.js:87:29)
    at async /Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:16:18
    at async /Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /Users/selcukcihan/serverless/console/node/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
    at async trysts (/Users/selcukcihan/serverless/console/node/test/python/aws-lambda-sdk/trysts.js:4:20) {
  tryNextLink: false,
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

Whereas, if I run the script with node, it works fine:

```
➜  aws-lambda-sdk git:(sc-356-integ-test) ✗ node trysts.js                                 
692593327170
692593327170
```

This is the minimal script I have, where I can reproduce the issue with aws-sdk configuration

```
const { STSClient, GetCallerIdentityCommand } = require("@aws-sdk/client-sts")
async function trysts() {
    const client = new STSClient()
    const result = await client.send(new GetCallerIdentityCommand())
    return result
}
trysts().then(x => console.log(x.Account)).catch(err => console.log(err))

const awsRequest = require('../../utils/aws-request')
const { STS } = require('@aws-sdk/client-sts')
awsRequest(STS, 'getCallerIdentity').then(x => console.log(x.Account)).catch(err => console.log(err))
```

I've tried setting `AWS_SDK_LOAD_CONFIG`, I've also tried setting the AWS credentials, I've tried using AWS_PROFILE as well. In each case, I'm getting the same error when invoked with `mocha`.

**Comment by medikoo** [comment]
@selcukcihan AWS credentials need to be in form of `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env variables. Reason for that is that tests do not see your home folder (for test isolation purposes the home folder is mocked to some temp directory), so whatever you have in `~/.aws`, test run won't see it.

I've put instructions on how to run those tests here: https://github.com/serverless/console/pull/483#issue-1606662500

**Comment by selcukcihan** [comment]
> @selcukcihan AWS credentials need to be in form of `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env variables reason for that is that tests do not see your home folder (for test isolation purposes the home folder is mocked to some temp directory), so whatever you have in `~/.aws`, test run won't see it.
> 
> I've put instructions on how to run those tests here: [#483 (comment)](https://github.com/serverless/console/pull/483#issue-1606662500)

🙏 works fine 👍

**Comment by medikoo** [comment]
> Yes, currently I'm working with Python3.9 only.

@selcukcihan Requirement is that we offer a solution that works on Python runtimes as available on AWS. Let's move this discussion to Linear

**Comment by medikoo** [comment]
> The error you got mentions a package named paddlepaddle which is not a dependency of our package, not even transiently. I think this is a problem with your python environment, can you try the steps I mentioned above and try to build it in a fresh virtual environment please?

@selcukcihan I've actually just followed the steps I found in CI workflow (and otherwise I do not use Python at all).

Let's get back to this discussion if we see similar warning in CI log

**Comment by selcukcihan** [comment]
@medikoo I've pushed some more fixes and then ran the integration tests by merging the integration test branch on my local branch. Tests are passing now (I've commented out tests for python v3.7 & v3.8):

```
(.venv) ➜  aws-lambda-sdk git:(sc-356-integ-test-2) ✗ ../../../node_modules/mocha/bin/mocha integration.test.js
2023-03-07T06:13:15.115Z ℹ test test uid: cdab


  Python: integration
2023-03-07T06:13:15.213Z ℹ test Creating core resources test-python-sdk-cdab
2023-03-07T06:14:11.594Z ℹ test Process function success-v3-9
2023-03-07T06:14:11.596Z ℹ test Process function error-v3-9
    ✔ success-v3-9 (29164ms)
    ✔ error-v3-9
2023-03-07T06:14:40.768Z ℹ test Cleanup test-python-sdk-cdab
2023-03-07T06:14:41.156Z ℹ test Deleted 14 version of the layer test-python-sdk-cdab-internal
2023-03-07T06:14:42.280Z ℹ test Detached IAM policy arn:aws:iam::692593327170:policy/test-python-sdk-cdab from test-python-sdk-cdab
2023-03-07T06:14:42.523Z ℹ test Deleted IAM role test-python-sdk-cdab
2023-03-07T06:14:43.101Z ℹ test Deleted IAM policy arn:aws:iam::692593327170:policy/test-python-sdk-cdab


  2 passing (1m)
```

**Comment by medikoo** [comment]
@selcukcihan what are the minimal steps to install this package locally for integration steps run?

**Comment by medikoo** [comment]
Additionally, can we run it against `sdk` and `sdk-schema` as they are in the repository?

e.g. in the Node.js case locally, I can run integration tests against the main package and its dependencies being taken from the repository (for that I have those dependent packages symlinked in `node_modules` folder). While, if dependencies are installed from npm, then I test against what's published (and that's the test which is also pursued in CI)

**Comment by selcukcihan** [comment]
> @selcukcihan what are the minimal steps to install this package locally for integration steps run?

1. Merge 0302-python-integration-tests branch to get the integration tests in
2. `cd python/packages`
3. `python3.9 -m venv .venv`
4.
```
export SLS_ORG_ID=test-org 
export AWS_REGION=us-east-1
export AWS_ACCESS_KEY_ID=...
export AWS_SECRET_ACCESS_KEY=...
```
5. `cd ../../node/test/python/aws-lambda-sdk`
6. Comment out tests except for v3.9
7. `../../../node_modules/mocha/bin/mocha integration.test.js`

**Comment by selcukcihan** [comment]
> Additionally, can we run it against `sdk` and `sdk-schema` as they are in the repository?
> 
> e.g. in the Node.js case locally, I can run integration tests against the main package and its dependencies being taken from the repository (for that I have those dependent packages symlinked in `node_modules` folder). While, if dependencies are installed from npm, then I test against what's published (and that's the test which is also pursued in CI)

To run them against local repository version of packages, we'd need to install them as such in the build-layer-archive.sh:

Just added a line for base sdk as an example: `python3 -m pip install $SCRIPT_DIR/../../sdk --target=$INSTALL_DIR`

```
#!/usr/bin/env bash
set -Eeuo pipefail

DIST=$(mktemp -d)  # directory to store intermediate artifacts
CURRENT_DIR=$(pwd)

case $1 in
  /*) OUTPUT=$1 ;;
  *) OUTPUT=$CURRENT_DIR/$1 ;;
esac

SITE_PACKAGES_DIR=python/lib/python3.9/site-packages
mkdir -p $DIST/{$SITE_PACKAGES_DIR,sls-sdk-python}

INSTALL_DIR=$DIST/$SITE_PACKAGES_DIR

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
python3 -m pip install $SCRIPT_DIR/../../sdk --target=$INSTALL_DIR
python3 -m pip install $SCRIPT_DIR/.. --target=$INSTALL_DIR

cp $INSTALL_DIR/serverless_aws_lambda_sdk/internal_extension/__init__.py $DIST/sls-sdk-python
cp $INSTALL_DIR/serverless_aws_lambda_sdk/internal_extension/base.py $DIST/sls-sdk-python
cp $INSTALL_DIR/serverless_aws_lambda_sdk/internal_extension/exec_wrapper.py $DIST/sls-sdk-python
cp $INSTALL_DIR/typing_extensions.py $DIST/sls-sdk-python
cp -R $INSTALL_DIR/strenum $DIST/sls-sdk-python

mkdir -p $(dirname $OUTPUT)


cd $DIST
zip -r $OUTPUT python sls-sdk-python
cd $CURRENT_DIR

rm -rf $DIST
```

**Comment by medikoo** [comment]
@selcukcihan thanks, that worked. Concerning minimal steps. I just wonder, why I didn't need to setup any dependences?
Python during execution automatically taken `sdk` and `sdk-schema` and other dependencies from PyPI?

**Comment by selcukcihan** [comment]
> @selcukcihan thanks, that worked. Concerning minimal steps. I just wonder, why I didn't need to setup any dependences?
> Python during execution automatically taken `sdk` and `sdk-schema` and other dependencies from PyPI?

Yes `build-layer-archive.sh` takes all the dependencies of aws-lambda-sdk (including sdk and sdk-schema) from pypi. aws-lambda-sdk is installed from local repository.

**Comment by medikoo** [comment]
>  Yes build-layer-archive.sh takes all the dependencies of aws-lambda-sdk (including sdk and sdk-schema) from pypi. aws-lambda-sdk is installed from local repository.

I think `build-layer-archive.sh` should assume that dependences are already installed (it's how Node.js script works), so we have possibility to build archive  relying either on deps from PyPI, or deps from repository (and latter is very convenient when e.g. you want to confirm with integration tests that changes as being in made in e.g. `sdk` work properly).

Do you think we can do that?

Additionally after running it, I end with untracked files in a repository, can we ensure those are git ignored?

Screenshot 2023-03-07 at 10 20 27

**Comment by selcukcihan** [comment]
> > Yes build-layer-archive.sh takes all the dependencies of aws-lambda-sdk (including sdk and sdk-schema) from pypi. aws-lambda-sdk is installed from local repository.
> 
> I think `build-layer-archive.sh` should assume that dependences are already installed (it's how Node.js script works), so we have possibility to build archive relying either on deps from PyPI, or deps from repository (and latter is very convenient when e.g. you want to confirm with integration tests that changes as being in made in e.g. `sdk` work properly).
> 
> Do you think we can do that?
> 
> Additionally after running it, I end with untracked files in a repository, can we ensure those are git ignored?
> 
> Screenshot 2023-03-07 at 10 20 27

For the untracked files, I had added .gitignore with https://github.com/serverless/console/pull/486/commits/82b8e35b9a4d8891d12a47d7c108abb60fdcb477 when you mentioned previously, is it not working for you? 

For the build script, yes I think that makes a lot of sense. I'll try to come up with a solution for that, I'll look into what we have in the node CI workflow to get a better understanding. But I don't recall the node workflow running integration tests for the base SDK package changes, maybe something I overlooked.

**Comment by medikoo** [comment]
> But I don't recall the node workflow running integration tests for the base SDK package changes, maybe something I overlooked.

Yes, it's not the case. In CI we validate SDK package changes, only after we upgrade the AWS Lambda SDK to rely on new version of SDK (integration tests are run just in context of AWS Lambda SDK)

Still for dev purposes it's important to have some straightforward way to confirm that changes in SDK do not break AWS Lambda SDK when we develop them.

So ideally if build step is deps installation method agnostic, and that this step is taken out of build script.

Can you also add documentation for this package in this PR? It'll be great also if we have test dedicated documentation (possibly in `test/index.md`) that outlines how to (1) install deps from PyPI or (2) how to ensure that deps are taken from repository (3) what are other steps that needed to run the tests.

**Comment by selcukcihan** [comment]
> > But I don't recall the node workflow running integration tests for the base SDK package changes, maybe something I overlooked.
> 
> Yes, it's not the case. In CI we validate SDK package changes, only after we upgrade the AWS Lambda SDK to rely on new version of SDK (integration tests are run just in context of AWS Lambda SDK)
> 
> Still for dev purposes it's important to have some straightforward way to confirm that changes in SDK do not break AWS Lambda SDK when we develop them.
> 
> So ideally if build step is deps installation method agnostic, and that this step is taken out of build script.
> 
> Can you also add documentation for this package in this PR? It'll be great also if we have test dedicated documentation (possibly in `test/index.md`) that outlines how to (1) install deps from PyPI or (2) how to ensure that deps are taken from repository (3) what are other steps that needed to run the tests.

* I've added lambda sdk docs
* I've added a readme within the "tests" directory. We can link to the integration tests which are located under the "node" top-level directory, so left it as a todo for now until we merge the integration test branch.
* I've removed the pip install directives from the build script. The script assumes dependencies are preinstalled. That's why I've also changed the publish lambda SDK CI flow to build the dependencies before running the script.

**Review by medikoo — CHANGES_REQUESTED** [review]
@selcukcihan that looks great.

Let's just add one last thing. I've merged the integration tests setup (I've removed for timebeing testing 3.7 and 3.8 from test). Can you configure `integration` build in CI so this integration test is run on merge?

**Comment by selcukcihan** [comment]
> @selcukcihan that looks great.
> 
> Let's just add one last thing. I've merged the integration tests setup (I've removed for timebeing testing 3.7 and 3.8 from test). Can you configure `integration` build in CI so this integration test is run on merge?

I've added the steps 👍

**Review by medikoo — APPROVED** [review]
👍

**Comment by medikoo** [comment]
@selcukcihan I've just merged and CI failed https://github.com/serverless/console/actions/runs/4353767482

As I see, it failed on unit tests, so technically, it should also not pass the validation step. Do you understand why unit tests passed in PR validation while failed in integration CI?

**Comment by selcukcihan** [comment]
> @selcukcihan I've just merged and CI failed https://github.com/serverless/console/actions/runs/4353767482
> 
> As I see, it failed on unit tests, so technically, it should also not pass the validation step. Do you understand why unit tests passed in PR validation while failed in integration CI?

Yeah I was checking that, I think it's because in the PR validation it uses Python 3.9, whereas in the integration CI it's v3.7. The code is not v3.7 ready (as we can tell from the failing tests). I'll try to switch to 3.9 in the CI

**Comment by selcukcihan** [comment]
@medikoo  I've created https://github.com/serverless/console/pull/493 for a resolution

**Comment by medikoo** [comment]
@selcukcihan I've merged the resolution PR and triggered the integration run by committing in small docs improvement, and CI failed with what's most likely missing env vars setup: https://github.com/serverless/console/actions/runs/4354378208/jobs/7609610536 (?)

**Comment by selcukcihan** [comment]
> @selcukcihan I've merged the resolution PR and triggered the integration run by committing in small docs improvement, and CI failed with what's most likely missing env vars setup: https://github.com/serverless/console/actions/runs/4354378208/jobs/7609610536 (?)

I'm looking into it, I was a bit optimistic in not testing this. I've reproduced it in my GitHub, will make sure it works and create another PR.

**Comment by selcukcihan** [comment]
@medikoo https://github.com/serverless/console/pull/494 for adding the env variables on the CI workflow.

**Comment by medikoo** [comment]
@selcukcihan Integration tests passed now 🎉  I think we can follow up with first release

**Comment by selcukcihan** [comment]
> @selcukcihan Integration tests passed now 🎉 I think we can follow up with first release

https://github.com/serverless/console/pull/495 for the release

**Pull request merged**
