### PR TITLE
[Python] Lambda SDK flask instrumentation

### PR DESCRIPTION
**Pull request by selcukcihan**
To be updated to latest base SDK (https://github.com/serverless/console/pull/642) before finalizing this PR. 

### Description
* Related issue https://linear.app/serverless/issue/SC-691/python-sdk-instrument-flask
* Adds integration tests for flask

### Testing done
Ran the integration tests against my account

### CODE REVIEW

**Comment by selcukcihan** [comment]
@medikoo ready for review please

**Review by medikoo — APPROVED** [review]
Looks good 👍

**Comment by medikoo** [comment]
@selcukcihan If I see correctly this just adds integration tests, while Flask instrumentation is already fully implemented and initializated in the context of `serverless-sdk` package.

**Comment by selcukcihan** [comment]
> @selcukcihan If I see correctly this just adds integration tests, while Flask instrumentation is already fully implemented and initializated in the context of `serverless-sdk` package.

That's correct 👍

**Pull request merged**
