### PR TITLE
Use event emitter for storing captured events

### PR DESCRIPTION
**Pull request by selcukcihan**
Related issue https://linear.app/serverless/issue/SC-311/python-sdk-captured-errors-and-warnings-api

### Description
Use the new functionality to store captured events.

### Testing done
Unit & integration tested

### CODE REVIEW

**Comment by selcukcihan** [comment]
@medikoo ready for review please 🙏

**Review by medikoo — COMMENTED** [review]
Will it work before doing a new release on SDK side?

**Comment by selcukcihan** [comment]
> Will it work before doing a new release on SDK side?

Yes, it will work and unit tests confirm that it works.

**Review by medikoo — APPROVED** [review]
👍

**Pull request merged**
