### PR TITLE
(SC-372) SDK: Document and publish v0.1.0

### PR DESCRIPTION
**Pull request by selcukcihan**
### Description
Related issue https://linear.app/serverless/issue/SC-372/sdk-document-and-publish-v010
* Add manually created changelog for the initial 0.1.0 version
* Bump serverless-sdk version to 0.1.0
* Add docs for python serverless-sdk package.

Note that the base sdk is missing some features, for instance `.instrumentation` is just a placeholder. As such I haven't completed those parts of the API in documentation.

### Testing done
N/A

### CODE REVIEW

**Review by medikoo — CHANGES_REQUESTED** [review]
Thanks @selcukcihan. It looks very good (if it gets to tedious there's no need to link GitHub commits in changelog - I know it can turn time taking to patch this by hand)

Let's just address this CI failure. I think we probably need to use `-` as a separator in package names (ideally if this patch comes with other PR, and here we focus just on docs and release)

**Review by medikoo — APPROVED** [review]
Looks great 👍  Now let's see if our publication script works :)

**Comment by selcukcihan** [comment]
> Looks great 👍 Now let's see if our publication script works :)

Something's not right, I'm checking. The filters somehow did not detect changes in the sdk folder. Thus the integrate flow did not push a tag.

**Comment by medikoo** [comment]
> Something's not right, I'm checking. The filters somehow did not detect changes in the sdk folder. Thus the integrate flow did not push a tag.

Sure, that's not a big deal, and I find it rare for sophisticated CI setup to run perfectly from first run. Let's go with following steps:
1. Coin and fix the issue on why path changes were not detected (I think you can play with it in a PR by setting up a temporary workflow never to be merged)
2. Issue tag manually to trigger the publish job (I will cover that)

**Comment by medikoo** [comment]
@selcukcihan As I look at this, this might have been caused by action I've made. I squashed the first release commit with a wrong message, so I canceled the build, amended the message, and pushed again. 

Maybe `dorny/path-filters` in the second build was comparing the commit state against the previous `main` build` and not its state in the repository (?) In such case, it won't see any changes.

Let me know. I think we can assume that, and I'll just manually push the tag to move forward with this

**Comment by selcukcihan** [comment]
> > Something's not right, I'm checking. The filters somehow did not detect changes in the sdk folder. Thus the integrate flow did not push a tag.
> 
> Sure, that's not a big deal, and I find it rare for sophisticated CI setup to run perfectly from first run. Let's go with following steps:
> 
> 1. Coin and fix the issue on why path changes were not detected (I think you can play with it in a PR by setting up a temporary workflow never to be merged)
> 2. Issue tag manually to trigger the publish job (I will cover that)

Cool, I've created https://github.com/serverless/console/pull/469 to address the first item ☝️

**Comment by selcukcihan** [comment]
> @selcukcihan As I look at this, this might have been caused by action I've made. I squashed the first release commit with a wrong message, so I canceled the build, amended the message, and pushed again.
> 
> Maybe `dorny/path-filters` in the second build was comparing the commit state against the previous `main` build` and not its state in the repository (?) In such case, it won't see any changes.
> 
> Let me know. I think we can assume that, and I'll just manually push the tag to move forward with this

Just saw your comment now, yeah that might explain it. In any case, https://github.com/serverless/console/pull/469 would be good to have as it's how integrate flow is set up for nodejs.

**Comment by medikoo** [comment]
@selcukcihan I've pushed the tag, let's see if publication goes well

**Comment by medikoo** [comment]
@selcukcihan It failed because apparently `serverless-sdk` is already published, and as I checked, it appears you've published it in the context of your account: https://pypi.org/project/serverless-sdk/

It's not great that you tested the name we were about to take. How can we recover from that? Can you pass the project name to the `serverless` user, so we can release v0.1.1 in context of our account?

**Comment by selcukcihan** [comment]
> @selcukcihan It failed because apparently `serverless-sdk` is already published, and as I checked, it appears you've published it in the context of your account: https://pypi.org/project/serverless-sdk/
> 
> It's not great that you tested the name we were about to take. How can we recover from that? Can you pass the project name to the `serverless` user, so we can release v0.1.1 in context of our account?

Oh no, this must have been triggered on my GitHub account somehow. When I was doing the tests, I had prefixed the packages with `selcuk_`. I've now removed my pypi token from my GitHub environment secrets to make sure this does not happen again.

I'm now looking into how we can pass the project name to serverless.

Edit: I think what happened is, when I synced my repo to serverless, my GitHub action was triggered because there was a version bump on main.

**Comment by selcukcihan** [comment]
I've invited "serverless". I can remove myself when serverless has access.

Screenshot 2023-02-22 at 14 59 09

**Comment by medikoo** [comment]
@selcukcihan thank you! It all seems good now. Can you then prepare PR with v0.1.1 release, so we have it properly released?

**Comment by selcukcihan** [comment]
> @selcukcihan thank you! It all seems good now. Can you then prepare PR with v0.1.1 release, so we have it properly released?

👌 https://github.com/serverless/console/pull/471 for the release

**Pull request merged**
