### PR TITLE
fix: Use correct regex for tag name validation

### PR DESCRIPTION
**Pull request by alexdelorenzo**
This PR contains these changes:
 - Fix tag name validation by using the correct regex
 - Fix tests to reflect validation changes

### CODE REVIEW

**Comment by alexdelorenzo** [comment]
@medikoo Added a bug-fix that `sc-356` made apparent

**Review by medikoo — APPROVED** [review]
Thanks @alexdelorenzo !

**Comment by medikoo** [comment]
@alexdelorenzo after we've merged that integration tests started to fail

**Comment by alexdelorenzo** [comment]
> @alexdelorenzo after we've merged that integration tests started to fail

@medikoo I looked at the Actions logs and it looks like that could be related to: https://github.com/serverless/console/pull/405

**Pull request merged**
