### PR TITLE
SDK:  `serverless.setTag` implementation

### PR DESCRIPTION
**Pull request by medikoo**
_Relies on #383_

### CODE REVIEW

**Review by Danwakeem — COMMENTED** [review]
This would also need to be include in the typescript file and documented in the readme, or is the coming in a follow up PR?

**Comment by medikoo** [comment]
> This would also need to be include in the typescript file and documented in the readme, or is the coming in a follow up PR?

Good call, forgot about that! Added

**Review by Danwakeem — COMMENTED** [review]
The types look good 😎 Would we also want to add a description for this function in the [sdk docs](https://github.com/serverless/console/blob/main/node/packages/sdk/docs/sdk.md)?

**Comment by medikoo** [comment]
> The types look good 😎 Would we also want to add a description for this function in the sdk docs?

Not sure where my head was :) great you've pointed that. Added

**Review by Danwakeem — APPROVED** [review]
Looks great 🚀

**Pull request merged**
