### PR TITLE
chore: Release v0.4.2

### PR DESCRIPTION
**Pull request by Danwakeem**
## Description
Releasing the update to the timeout message

### CODE REVIEW

**Review by medikoo — COMMENTED** [review]
@Danwakeem please see https://github.com/serverless/console/pull/72#discussion_r897652966

I think we should rather not include `errorExceptionStacktrace` in case of a timeout

**Comment by Danwakeem** [comment]
@medikoo i agree but we do end up using this field on the frontend to display the timeout error message. I think switching the error message and error stack trace fields is another issue all together.

I could work on that bug today and include that in this release 👍

**Comment by medikoo** [comment]
> @medikoo i agree but we do end up using this field on the frontend to display the timeout error message. I think switching the error message and error stack trace fields is another issue all together.


I think on a frontend logic should be as:

```javascript
if (errorType === 'timeout') {
  show("Lambda timed out")
} else {
  show(errorMesssage):
  if (errorStackTrace) show(errorStackTrace)
}
```

**Comment by Danwakeem** [comment]
@medikoo sure we could do that. I will just close this out.

**Pull request closed without merging**
