### PR TITLE
Release AWS Lambda SDK v0.1.6

### PR DESCRIPTION
**Pull request by selcukcihan**
Related issue https://linear.app/serverless/issue/SC-560/ensure-support-for-python-38#comment-76ad2b27

### CODE REVIEW

**Review by medikoo — CHANGES_REQUESTED** [review]
In a meantme I've also merged https://github.com/serverless/console/pull/508  So I believe it also needs to be covered in changelog

**Comment by selcukcihan** [comment]
@medikoo now that we've introduced breaking changes, the actions in this PR are failing as unit tests run against the latest code in the repo and do not rely on the version declared in the project config.

What do you think, should we first adapt lambda SDK to these new changes and after that release v0.1.6? Or should we change the CI flow such that if there's no code change, if it's just changelog and version bump then not run unit tests? Or another course of action is to run unit tests using all dependencies from PyPI instead of relying on local repo?

**Comment by medikoo** [comment]
> @medikoo now that we've introduced breaking changes, the actions in this PR are failing as unit tests run against the latest code in the repo and do not rely on the version declared in the project config

So we need to first fix update `aws-lambda-sdk`

Do you also mean that https://github.com/serverless/console/pull/511 was not ready for review and merge? If so we need establish some solid workflow to avoid such issues.

Can we agree that when you propose a PR you always (after CI is green) walso comment stating that it's ready for review (just the first time - on re-review requests you can re-request review in reviewers box)

**Comment by medikoo** [comment]
> @medikoo now that we've introduced breaking changes, the actions in this PR are failing as unit tests run against the latest code in the repo and do not rely on the version declared in the project config.

@selcukcihan, actually, just realized, unit tests should also test against PyPi version of dependencies, can we fix that?

**Comment by selcukcihan** [comment]
> > @medikoo now that we've introduced breaking changes, the actions in this PR are failing as unit tests run against the latest code in the repo and do not rely on the version declared in the project config.
> 
> @selcukcihan, actually, just realized, unit tests should also test against PyPi version of dependencies, can we fix that?

Yeah I was thinking the same, will create the PR and then we can test this release 🤞

**Comment by selcukcihan** [comment]
@medikoo ready for review please

**Review by medikoo — APPROVED** [review]
👍

**Pull request merged**
