### PR TITLE
[Python base SDK] Switch to using version file

### PR DESCRIPTION
**Pull request by selcukcihan**
### Description
* Related issue https://linear.app/serverless/issue/SC-593/python-sdk-big-latency-overhead#comment-ed4329da
* Similar PR https://github.com/serverless/console/pull/719
* Use VERSION file instead of relying on importlib_metadata to figure out the version.
* Add a unit test that makes sure hard-coded value matches the project config's value.

### Testing done
Unit tested

### CODE REVIEW

**Comment by selcukcihan** [comment]
@medikoo ready for review please

**Review by medikoo — COMMENTED** [review]
Looks great, but what about CI detection?

Should we do it, in the next PR so it doesn't accidentally try to release new version?

**Comment by selcukcihan** [comment]
> Looks great, but what about CI detection?
> 
> Should we do it, in the next PR so it doesn't accidentally try to release new version?

Good point, checking it

**Comment by selcukcihan** [comment]
@medikoo I've disabled auto publish of new tag, we can enable after this is merged.

**Review by medikoo — APPROVED** [review]
👍

**Pull request merged**
