### PR TITLE
build(dev-mode): Upgrade Go module dependencies

### PR DESCRIPTION
**Pull request by Mmarzex**

### CODE REVIEW

**Review by medikoo — DISMISSED** [review]
👍

**Review by Danwakeem — APPROVED** [review]
😎

**Review by Danwakeem — DISMISSED** [review]
Lol didn't realize it was this far behind already. Thanks man 😎

**Comment by medikoo** [comment]
@Mmarzex @Danwakeem @czubocha This appears as never merged, is this still needed?

**Comment by czubocha** [comment]
@Mmarzex I've updated Go version and bumped module deps, I think we can merge it

**Review by Danwakeem — APPROVED** [review]

**Pull request merged**
