### PR TITLE
AWS Lambda SDK: Release v0.10.0

### PR DESCRIPTION
**Pull request by medikoo**

### CODE REVIEW

**Review by Danwakeem — APPROVED** [review]
:shipit:

**Comment by Mmarzex** [comment]
@Danwakeem Should we get a new sdk-schema version out with your changes and then publish this so we don't need to publish twice today?

**Comment by medikoo** [comment]
@Mmarzex @Danwakeem should I hold with merging this?

**Comment by Danwakeem** [comment]
@Mmarzex @medikoo I don't think so 🤔 the changes to the schema only appear to be affect the ingestion pipeline when we are enriching the data coming from the SDK/cloudwatch/external extension.

**Comment by Mmarzex** [comment]
Gotcha Sounds good, wasn't sure if we'd get out of sync.

**Pull request merged**
