### PR TITLE
Release python base sdk v0.3.2

### PR DESCRIPTION
**Pull request by selcukcihan**
To release the fix made with https://github.com/serverless/console/pull/542

### CODE REVIEW

**Comment by selcukcihan** [comment]
@medikoo ready for review please 🙏

**Comment by selcukcihan** [comment]
@medikoo let's wait on this, I'm looking into something.

**Comment by selcukcihan** [comment]
@medikoo we can release this now

**Review by medikoo — APPROVED** [review]
👍

**Pull request merged**
