### PR TITLE
Include custom tags in trace

### PR DESCRIPTION
**Pull request by selcukcihan**
Related issue https://linear.app/serverless/issue/SC-564/python-sdk-custom-tags-api

### Description
* Include custom tags in trace
* Integration & unit test custom tags
* Upgrade to the latest base SDK version

### Testing done
Integration tested:
```
➜  node git:(include-custom-tags-in-trace) ✗ npx mocha test/python/aws-lambda-sdk/integration.test.js
2023-03-15T17:21:51.742Z ℹ test test uid: selcuk


  Python: integration
2023-03-15T17:21:51.836Z ℹ test Creating core resources test-python-sdk-selcuk
2023-03-15T17:22:27.777Z ℹ test Process function success-v3-8
2023-03-15T17:22:27.778Z ℹ test Process function success-v3-9
2023-03-15T17:22:27.778Z ℹ test Process function error-v3-8
2023-03-15T17:22:27.779Z ℹ test Process function error-v3-9
2023-03-15T17:22:27.779Z ℹ test Process function error_unhandled-v3-8
2023-03-15T17:22:27.779Z ℹ test Process function error_unhandled-v3-9
2023-03-15T17:22:27.780Z ℹ test Process function sdk-v3-8
2023-03-15T17:22:27.780Z ℹ test Process function sdk-v3-9
    ✔ success-v3-8 (29355ms)
    ✔ success-v3-9 (1117ms)
    ✔ error-v3-8
    ✔ error-v3-9
    ✔ error_unhandled-v3-8
    ✔ error_unhandled-v3-9
    ✔ sdk-v3-8
    ✔ sdk-v3-9 (5024ms)
2023-03-15T17:23:03.307Z ℹ test Cleanup test-python-sdk-selcuk
2023-03-15T17:23:03.651Z ℹ test Deleted 4 version of the layer test-python-sdk-selcuk-internal
2023-03-15T17:23:04.581Z ℹ test Detached IAM policy arn:aws:iam::692593327170:policy/test-python-sdk-selcuk from test-python-sdk-selcuk
2023-03-15T17:23:04.798Z ℹ test Deleted IAM role test-python-sdk-selcuk
2023-03-15T17:23:05.276Z ℹ test Deleted IAM policy arn:aws:iam::692593327170:policy/test-python-sdk-selcuk


  8 passing (1m)
```

### CODE REVIEW

**Comment by selcukcihan** [comment]
@medikoo ready for review please 🙏

**Review by medikoo — APPROVED** [review]
👍

**Comment by medikoo** [comment]
@selcukcihan can we follow up with a release?

**Comment by selcukcihan** [comment]
> @selcukcihan can we follow up with a release?

https://github.com/serverless/console/pull/533 👍

**Pull request merged**
